# Generated by Django 3.1.4 on 2021-01-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logindata',
        ),
    ]
